[target.riscv32i-unknown-none-elf]
# Enable the 'm' (multiplication/division) extension.
rustflags = [
  "-C", "target-feature=+m",
  "-C", "link-arg=-Tmemory.x",
]

[alias]
xtask = "run --release --target x86_64-unknown-linux-gnu --manifest-path xtask/Cargo.toml --"

[build]
target = "riscv32i-unknown-none-elf"